[profile.default]
src = "solidity/src"
test = "solidity/test"
out = "solidity/out"
libs = [ "solidity/lib" ]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
  "forge-std/=solidity/lib/devtools/packages/toolbox-foundry/src/forge-std/src/",
  "@openzeppelin/contracts-upgradeable/=solidity/lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=solidity/lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@layerzerolabs/lz-evm-protocol-v2/=solidity/lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
  '@layerzerolabs/lz-evm-messagelib-v2/=solidity/lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/',
  "@layerzerolabs/oapp-evm/=solidity/lib/devtools/packages/oapp-evm/",
  "@layerzerolabs/oft-evm/=solidity/lib/devtools/packages/oft-evm/",
  "@layerzerolabs/oapp-evm-upgradeable/=solidity/lib/devtools/packages/oapp-evm-upgradeable/",
  "@layerzerolabs/oft-evm-upgradeable/=solidity/lib/devtools/packages/oft-evm-upgradeable/",
  "@layerzerolabs/test-devtools-evm-foundry/=solidity/lib/devtools/packages/test-devtools-evm-foundry/",
  "@layerzerolabs/lz-evm-v1-0.7/=solidity/lib/LayerZero-v1/",
  "solidity-bytes-utils/=solidity/lib/solidity-bytes-utils/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
