include = [ "taplo.toml", "**/Cargo.toml", "**/foundry.toml", "rustfmt.toml", "../.github/typos.toml" ]
exclude = [ "solidity/lib/**" ]

[formatting]
align_entries       = true
compact_arrays      = false
array_auto_expand   = false
array_auto_collapse = false
